name: green_recipe
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

#------------Packages------------#
dependencies:
  flutter:
    sdk: flutter

  #--------Icons--------#
  iconsax: ^0.0.8
  lottie: ^2.7.0
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  fluttertoast: ^8.2.4
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  page_transition: ^2.1.0
  carousel_slider: ^4.0.0
  shimmer: ^2.0.0
  ionicons: ^0.2.2
  provider: ^6.1.1
  image_picker: ^1.0.4
  cloud_firestore: ^4.13.1
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0


flutter:


  uses-material-design: true

#------------Local Assets------------#
  assets:
    - assets/images/
    - assets/images/loginLogo/
    - assets/images/animations/
    - assets/images/onboard/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages